#!/usr/bin/env bash
# configures nginx and adds an X-Served-By response header with the server's hostname
# shellcheck disable=SC2154
apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!" | tee /var/www/html/index.html
if ! grep -q "X-Served-By" /etc/nginx/sites-available/default; then
    sed -i "0,/server_name _;/s|server_name _;|server_name _;\n\tadd_header X-Served-By \$hostname;|" /etc/nginx/sites-available/default
fi
nginx -t && service nginx restart
