#!/usr/bin/env bash
# installs and configures HAProxy to load balance between web-01 and web-02
apt-get update -y
apt-get install -y haproxy

# Enable HAProxy to start via init script
echo "ENABLED=1" > /etc/default/haproxy

cat >> /etc/haproxy/haproxy.cfg << EOF

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7188-web-01 54.172.105.250:80 check
    server 7188-web-02 100.26.183.147:80 check
EOF

service haproxy restart
