#!/usr/bin/env bash
# installs and configures HAProxy to load balance between web-01 and web-02
apt-get update -y
apt-get install -y haproxy

# Enable HAProxy to be managed via init script
echo "ENABLED=1" > /etc/default/haproxy

# Map web-01 and web-02 hostnames to their real IP addresses
if ! grep -q "web-01" /etc/hosts; then
    echo "54.172.105.250 web-01" >> /etc/hosts
fi
if ! grep -q "web-02" /etc/hosts; then
    echo "100.26.183.147 web-02" >> /etc/hosts
fi

cat >> /etc/haproxy/haproxy.cfg << EOF

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 web-01:80 check
    server web-02 web-02:80 check
EOF

haproxy -c -f /etc/haproxy/haproxy.cfg && service haproxy restart
